export const ICON_MAP: { [key: string]: string } = {
  'Family Medicine': 'home',
  'Heart Checkup': 'favorite',
  'Neurological Consultation': 'psychology',
  'Bone Fracture Treatment': 'accessible',
  'Pediatric General Checkup': 'child_care',
  'Digestive System Analysis': 'restaurant',
  'Skin Condition Diagnosis': 'palette',
  'Mental Health Therapy': 'self_improvement',
  'Prenatal Checkup': 'pregnant_woman',
  'Hormonal Therapy Session': 'science',
  'Cancer Screening': 'coronavirus',
  'ECG Test': 'monitor_heart',
  'EEG Test': 'device_hub',
  'Physical Therapy Session': 'sports_kabaddi',
  'Child Vaccination': 'vaccines',
  'Endoscopy': 'search',
  'Acne Treatment': 'healing',
  'Psychiatric Evaluation': 'support',
  'Gynecological Consultation': 'female',
  'Diabetes Management': 'insights',
  'Chemotherapy Session': 'biotech',
  'Diagnostic Testing': 'science',
  'Blood Sample Collection': 'opacity',
  'Preoperative Anesthesia Consultation': 'local_hospital',
  'General Anesthesia Administration': 'hotel',
  'X-ray Imaging': 'filter_hdr',
  'CT Scan': 'camera_indoor',
  'Urinary Tract Infection Treatment': 'wc',
  'Prostate Health Consultation': 'male',
  'Eye Examination': 'visibility',
  'Cataract Surgery Consultation': 'visibility_off',
  'Lung Function Test': 'air',
  'Asthma Management': 'cloud',
  'Arthritis Consultation': 'accessibility',
  'Osteoporosis Treatment': 'elderly',
  'Allergy Testing': 'bug_report',
  'Immunotherapy': 'vaccines'
};
