export const ICON_MAP: { [key: string]: string } = {
  'Medycyna rodzinna': 'home',
  'Badanie serca': 'favorite',
  'Konsultacja neurologiczna': 'psychology',
  'Leczenie złamań kości': 'accessible',
  'Pediatryczne badanie ogólne': 'child_care',
  'Analiza układu pokarmowego': 'restaurant',
  'Diagnoza chorób skórnych': 'palette',
  'Terapia zdrowia psychicznego': 'self_improvement',
  'Badanie prenatalne': 'pregnant_woman',
  'Sesja terapii hormonalnej': 'science',
  'Badanie wczesnej diagnostyki nowotworowej': 'coronavirus',
  'Test EKG': 'monitor_heart',
  'Test EEG': 'device_hub',
  'Sesja terapii fizycznej': 'sports_kabaddi',
  'Szczepienie dzieci': 'vaccines',
  'Endoskopia': 'search',
  'Leczenie trądziku': 'healing',
  'Ocena psychiatryczna': 'support',
  'Konsultacja ginekologiczna': 'female',
  'Konsultacja diabetologiczna': 'insights',
  'Sesja chemioterapii': 'biotech',
  'Badania diagnostyczne': 'science',
  'Pobieranie próbki krwi': 'opacity',
  'Konsultacja przedoperacyjna anestezjologiczna': 'local_hospital',
  'Podanie znieczulenia ogólnego': 'hotel',
  'Obrazowanie rentgenowskie': 'filter_hdr',
  'Tomografia komputerowa (CT)': 'camera_indoor',
  'Leczenie infekcji dróg moczowych': 'wc',
  'Konsultacja zdrowia prostaty': 'male',
  'Badanie wzroku': 'visibility',
  'Konsultacja w sprawie operacji zaćmy': 'visibility_off',
  'Test funkcji płuc': 'air',
  'Konsultacja pulmonologiczna': 'cloud',
  'Konsultacja w sprawie artretyzmu': 'accessibility',
  'Leczenie osteoporozy': 'elderly',
  'Testy alergiczne': 'bug_report',
  'Immunoterapia': 'vaccines',
};
